name: Deploy to Demo
run-name: Deploy ${{ inputs.version }} to Demo by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      service:
        type: string
        description: "The service you want to deploy. dibbs-landing"
        required: true
        default: dibbs-landing
      version:
        type: string
        description: "The version to deploy. Example: v2.6.0 or main"
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        run: |
          repo_owner="skylight-hq" 
          repo_name="dibbs-tf-envs"  
          event_type="trigger-demo-deploy" 
          service="${{ github.event.inputs.service }}"
          version="${{ github.event.inputs.version }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DIBBS_SKYLIGHT_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"version\": \"$version\", \"service\": \"$service\"}}"
